modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "knockdowns"
version = "${version}"
displayName = "Knockdowns"
authors = "Octol1ttle"
description = '''
DNBO mechanic from Fortnite, ported to Minecraft
'''
#logoFile = ""

[[dependencies.knockdowns]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knockdowns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knockdowns]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"